In [5]:
import pandas as pd
 
df1 = pd.read_csv('/content/drive/MyDrive/ic/Dados - Indivíduos SNPs/adni_gwas_v2/adni_gwas_v2_set01/002_S_0295.csv', usecols=['SNP Name'])

In [6]:
df1

         SNP Name
0          200003
1          200006
2          200047
3          200050
4          200052
...           ...
620896  rs9999944
620897   rs999995
620898  rs9999963
620899  rs9999966
620900  rs9999979

[620901 rows x 1 columns]

In [4]:
df1[df1['SNP Name']== 'rs10127904']

       Sample Index   Sample ID  GC Score  ...  Y Raw B Allele Freq Log R Ratio
30399           373  002_S_0295    0.9115  ...    852        0.5179     -0.3218

[1 rows x 24 columns]

In [ ]:
df2 = pd.read_csv('/content/drive/MyDrive/ic/Dados - Indivíduos SNPs/adni_gwas_v2/adni_gwas_v2_set01/002_S_0295.csv')