In [1]:
import pandas as pd
 
df1 = pd.read_csv('/content/drive/MyDrive/ic/Dados - Indivíduos SNPs/adni_gwas_v2/adni_gwas_v2_set01/002_S_0295.csv', usecols=['SNP Name'])

In [2]:
df1

         SNP Name
0          200003
1          200006
2          200047
3          200050
4          200052
...           ...
620896  rs9999944
620897   rs999995
620898  rs9999963
620899  rs9999966
620900  rs9999979

[620901 rows x 1 columns]

In [ ]:
df1[df1['SNP Name']== 'rs10127904']

       Sample Index   Sample ID  GC Score  ...  Y Raw B Allele Freq Log R Ratio
30399           373  002_S_0295    0.9115  ...    852        0.5179     -0.3218

[1 rows x 24 columns]

In [6]:
df2 = pd.read_csv('/content/drive/MyDrive/ic/Dados - Indivíduos SNPs/adni_gwas_v2/adni_gwas_v2_set01/002_S_0295.csv',usecols = ["SNP Name"])
df2

         SNP Name
0          200003
1          200006
2          200047
3          200050
4          200052
...           ...
620896  rs9999944
620897   rs999995
620898  rs9999963
620899  rs9999966
620900  rs9999979

[620901 rows x 1 columns]

Verificando se o SNPs de diferentes individuos são sempre os mesmos

In [19]:
meu_indexador = df1["SNP Name"].isin(df2["SNP Name"])
meu_indexador

0         True
1         True
2         True
3         True
4         True
          ...
620896    True
620897    True
620898    True
620899    True
620900    True
Name: SNP Name, Length: 620901, dtype: bool

In [ ]:
import os
folders = os.listdir('/content/drive/My Drive/ic/Dados - Indivíduos SNPs/adni_gwas_v2')
folders.sort()
folders

In [25]:
diferentes = 0 
iguais = 0
for folder in folders:
  file = os.listdir(f'/content/drive/My Drive/ic/Dados - Indivíduos SNPs/adni_gwas_v2/{folder}') #procura mais profundamente todos os .csv em todas as pastas indicadas
  file.sort()
  for id in file: #pego cada um dos cerca de 200 arquivos
    teste = pd.read_csv(f'/content/drive/My Drive/ic/Dados - Indivíduos SNPs/adni_gwas_v2/{folder}/{id}',usecols=["SNP Name"]) 
    indexador = df1["SNP Name"].isin(teste["SNP Name"])
    if (indexador.sum() != teste["SNP Name"].count()): 
      diferentes +=1
    else:
      iguais += 1

In [29]:
print(f'Iguais: {iguais} \nDiferentes: {diferentes}')

Iguais: 757
Diferentes: 0

**Portanto todos os individuos têm os mesmos SNPs**

---